version: '3.7'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: test
      MONGODB_APPLICATION_DATABASE: sample
      MONGODB_APPLICATION_USER: aashrey
      MONGODB_APPLICATION_PASS: admin123
    volumes:
      -  /docker-data:/data/db
      #- ./init-mongo.sh:/docker-entrypoint-initdb.d
      -  /db-init.js:/docker-entrypoint-initdb.d
    ports:
      - '27017:27017'
  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
        - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

volumes:
  docker-data:
    name: users-mogoDB-data